# Generated by Django 5.2.17 on 2026-09-25 23:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('return_type', models.CharField(choices=[('delivery_failed', 'Delivery Failed'), ('customer_rejected', 'Customer Rejected'), ('damaged_item', 'Damaged Item'), ('wrong_item', 'Wrong Item'), ('cancellation_after_dispatch', 'Cancellation After Dispatch')], max_length=30)),
                ('reason_code', models.CharField(choices=[('customer_unavailable', 'Customer Unavailable'), ('address_incorrect', 'Address Incorrect'), ('damaged_in_transit', 'Damaged in Transit'), ('customer_changed_mind', 'Customer Changed Mind'), ('item_mismatch', 'Item Mismatch')], max_length=24)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_transit', 'In Transit (Return)'), ('received', 'Received'), ('inspected', 'Inspected'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='initiated', max_length=12)),
                ('owner', models.CharField(choices=[('delivery', 'Delivery'), ('warehouse', 'Warehouse'), ('support', 'Support'), ('finance', 'Finance')], default='support', max_length=10)),
                ('item_details', models.CharField(max_length=255)),
                ('return_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('financial_impact', models.CharField(choices=[('refund_required', 'Refund Required'), ('replacement_required', 'Replacement Required'), ('no_refund', 'No Refund')], default='refund_required', max_length=24)),
                ('exception_flag', models.CharField(blank=True, choices=[('dispute', 'Dispute'), ('high_value_item', 'High-Value Item'), ('customer_complaint', 'Customer Complaint')], max_length=20)),
                ('item_condition', models.CharField(blank=True, choices=[('as_described', 'As described / resellable'), ('damaged', 'Damaged'), ('missing_parts', 'Missing parts'), ('used', 'Used / opened')], max_length=16)),
                ('inspection_notes', models.TextField(blank=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('resolution_notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='deliveries.delivery')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_returns', to=settings.AUTH_USER_MODEL)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.order')),
                ('refund_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunded_return', to='orders.payment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('owner', models.CharField(choices=[('delivery', 'Delivery'), ('warehouse', 'Warehouse'), ('support', 'Support'), ('finance', 'Finance')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='returns.returnrequest')),
            ],
            options={
                'verbose_name_plural': 'return status history',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['owner'], name='returns_ret_owner_df23fa_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['handler'], name='returns_ret_handler_11cba6_idx'),
        ),
    ]
