# Generated by Django 5.2.17 on 2026-09-29 20:23

import apps.returns.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_multivendor'),
        ('orders', '0007_production_readiness'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='customer_message',
            field=models.TextField(blank=True, help_text='What AGIZA tells the customer (shown to them)'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='customer_note',
            field=models.TextField(blank=True, help_text="The customer's explanation"),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, help_text='Vendor earnings adjusted for the refund', null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='requested_by_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='restocked',
            field=models.BooleanField(default=False, help_text='Returned items were put back into sellable stock'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason_code',
            field=models.CharField(choices=[('customer_unavailable', 'Customer Unavailable'), ('address_incorrect', 'Address Incorrect'), ('damaged_in_transit', 'Damaged in Transit'), ('customer_changed_mind', 'Customer Changed Mind'), ('item_mismatch', 'Item Mismatch'), ('defective', "Defective / doesn't work"), ('not_as_described', 'Not as described'), ('seller_unavailable', "Seller couldn't supply the item")], max_length=24),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='return_type',
            field=models.CharField(choices=[('delivery_failed', 'Delivery Failed'), ('customer_rejected', 'Customer Rejected'), ('damaged_item', 'Damaged Item'), ('wrong_item', 'Wrong Item'), ('cancellation_after_dispatch', 'Cancellation After Dispatch'), ('customer_request', 'Customer Return Request'), ('seller_cannot_fulfill', "Seller Couldn't Fulfil")], max_length=30),
        ),
        migrations.CreateModel(
            name='ReturnAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.returns.models.return_attachment_path)),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_by_customer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='returns.returnrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.DecimalField(decimal_places=2, help_text='Value of these units as sold', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='orders.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='returns.returnrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnVendorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_responses', to='returns.returnrequest')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.vendor')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
