# Generated by Django 5.2.17 on 2026-09-25 23:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_reference_data'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_sourcing', 'Pending Sourcing'), ('supplier_selected', 'Supplier Selected'), ('paid', 'Paid'), ('supplier_cancelled', 'Supplier Canceled'), ('received_at_cargo', 'Received at Cargo'), ('cancelled', 'Cancelled')], db_index=True, default='pending_sourcing', max_length=20)),
                ('supplier_order_number', models.CharField(blank=True, help_text='Supplier invoice / PO number', max_length=80)),
                ('supplier_tracking_number', models.CharField(blank=True, max_length=80)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('item_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total paid to the supplier', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('payment_reference', models.CharField(blank=True, max_length=80)),
                ('exception_flag', models.CharField(blank=True, choices=[('payment_issue', 'Payment Issue'), ('supplier_delay', 'Supplier Delay'), ('quality_concern', 'Quality Concern'), ('stock_unavailable', 'Stock Unavailable')], max_length=20)),
                ('expected_at_cargo', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='procurement', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='procurement.procurementorder')),
            ],
            options={
                'verbose_name_plural': 'procurement status history',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='locations.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='procurementorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='procurement.supplier'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['country', 'is_active'], name='procurement_country_7e526e_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementorder',
            index=models.Index(fields=['operator'], name='procurement_operato_5af2b8_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementorder',
            index=models.Index(fields=['exception_flag'], name='procurement_excepti_f338b9_idx'),
        ),
    ]
