# Generated by Django 5.2.17 on 2026-10-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_backfill_procurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementorder',
            name='shipped_at',
            field=models.DateTimeField(blank=True, help_text='When the supplier shipped the goods', null=True),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='exception_flag',
            field=models.CharField(blank=True, choices=[('payment_issue', 'Payment Issue'), ('supplier_delay', 'Supplier Delay'), ('quality_concern', 'Quality Concern'), ('stock_unavailable', 'Stock Unavailable'), ('parcel_lost', 'Parcel Lost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='status',
            field=models.CharField(choices=[('pending_sourcing', 'Pending Sourcing'), ('supplier_selected', 'Supplier Selected'), ('paid', 'Paid'), ('supplier_shipped', 'Supplier Shipped'), ('supplier_cancelled', 'Supplier Canceled'), ('received_at_cargo', 'Received at Cargo'), ('cancelled', 'Cancelled')], db_index=True, default='pending_sourcing', max_length=20),
        ),
    ]
