# Generated by Django 5.2.17 on 2026-09-26 00:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0002_reference_data'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bin_code', models.CharField(blank=True, help_text='Shelf / bin (warehouse) or shelf position (shop)', max_length=60)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('listed', models.BooleanField(default=True, help_text='Shop floor: shown to customers in the shop')),
                ('shop_price', models.DecimalField(blank=True, decimal_places=2, help_text='Shop floor price; empty = product price', max_digits=14, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='locations.warehouse')),
            ],
            options={
                'ordering': ['warehouse__code', 'variant__sku'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Received'), ('adjustment', 'Adjustment'), ('reservation', 'Reserved for order'), ('release', 'Reservation released'), ('sale', 'Shipped / sold'), ('return', 'Returned to stock'), ('transfer_out', 'Transferred out'), ('transfer_in', 'Transferred in')], max_length=14)),
                ('quantity_change', models.IntegerField(default=0)),
                ('reserved_change', models.IntegerField(default=0)),
                ('quantity_after', models.IntegerField()),
                ('reserved_after', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.order')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('variant', 'warehouse'), name='uniq_stock_per_location'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_quantity_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__gte', 0), ('reserved__lte', models.F('quantity'))), name='stock_reserved_within_quantity'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item', 'created_at'], name='inventory_s_stock_i_c40196_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['order'], name='inventory_s_order_i_e9e6e3_idx'),
        ),
    ]
