# Generated by Django 5.2.17 on 2026-09-25 22:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('international', 'International Order'), ('express', 'Express Delivery'), ('equipment', 'Equipment Support')], max_length=16)),
                ('description', models.TextField()),
                ('origin', models.CharField(blank=True, help_text='Where goods come from, e.g. "China"', max_length=120)),
                ('destination', models.CharField(blank=True, help_text='e.g. "Dar es Salaam"', max_length=120)),
                ('status', models.CharField(choices=[('new', 'New Quotation'), ('waiting_reply', 'Waiting for Reply'), ('answered', 'Answered'), ('declined', 'Declined by Customer'), ('approved', 'Approved — Order Created'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=16)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('customer_replied_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_requests', to='parties.customer')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='quotes.quoterequest')),
            ],
            options={
                'verbose_name_plural': 'quote status history',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['status', '-requested_at'], name='quotes_quot_status_6ab072_idx'),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['service_type'], name='quotes_quot_service_982943_idx'),
        ),
    ]
