# Generated by Django 5.2.17 on 2026-10-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_request_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteattachment',
            name='from_agiza',
            field=models.BooleanField(default=False, help_text='Attached by staff to the quotation (shown to the customer)'),
        ),
    ]
