# Generated by Django 5.2.17 on 2026-09-29 17:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_multivendor'),
        ('locations', '0003_multivendor'),
        ('orders', '0005_shopdetails_delivery_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='catalog.category')),
            ],
            options={
                'ordering': ['category__name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text="AGIZA's commission on vendor sales when no category or vendor rate applies", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('require_product_review', models.BooleanField(default=True, help_text="Vendor products (and changes to what they show) wait for AGIZA's approval")),
                ('vendor_applications_open', models.BooleanField(default=True)),
                ('payout_schedule', models.CharField(blank=True, default='Weekly, for delivered and paid orders', help_text='Shown to vendors next to their earnings', max_length=160)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'marketplace settings',
            },
        ),
        migrations.CreateModel(
            name='VendorFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'New order'), ('accepted', 'Preparing'), ('ready', 'Ready for pickup'), ('shipped', 'Collected by AGIZA'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Gross merchandise value of these lines', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vendor_net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Part of the customer's delivery fee for these items (AGIZA revenue)", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('settlement_status', models.CharField(choices=[('pending', 'Pending (order not yet paid and delivered)'), ('payable', 'Payable'), ('settled', 'Paid out'), ('void', 'Void (order cancelled)')], db_index=True, default='pending', max_length=8)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='orders.order')),
                ('origin', models.ForeignKey(blank=True, help_text='Where AGIZA collects these items', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.warehouse')),
                ('vendor', models.ForeignKey(blank=True, help_text='Empty = sold by AGIZA', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments', to='catalog.vendor')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=10)),
                ('to_status', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('by_vendor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='marketplace.vendorfulfillment')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VendorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('method', models.CharField(choices=[('mobile_money', 'Mobile money'), ('bank', 'Bank transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=14)),
                ('transaction_reference', models.CharField(blank=True, max_length=80)),
                ('paid_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='catalog.vendor')),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='vendorfulfillment',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments', to='marketplace.vendorpayout'),
        ),
        migrations.CreateModel(
            name='VendorStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('by_vendor', models.BooleanField(default=False, help_text='Done by the vendor (application, resubmission)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='catalog.vendor')),
            ],
            options={
                'verbose_name_plural': 'vendor status history',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='vendorfulfillment',
            index=models.Index(fields=['vendor', 'status'], name='marketplace_vendor__898583_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorfulfillment',
            index=models.Index(fields=['vendor', 'settlement_status'], name='marketplace_vendor__a7d2a5_idx'),
        ),
    ]
