# Generated by Django 5.2.17 on 2026-09-29 20:23

import apps.marketplace.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_ledger(apps, schema_editor):
    """Post what already happened: earnings already payable or paid out, and payouts already made."""
    F = apps.get_model("marketplace", "VendorFulfillment")
    P = apps.get_model("marketplace", "VendorPayout")
    E = apps.get_model("marketplace", "VendorLedgerEntry")
    for f in F.objects.filter(vendor__isnull=False, settlement_status__in=["payable", "settled"]).select_related("order"):
        E.objects.get_or_create(key=f"earning:{f.pk}", defaults=dict(
            vendor_id=f.vendor_id, kind="earning", amount=f.vendor_net, gross_amount=f.subtotal,
            commission_amount=f.commission, fulfillment_id=f.pk, reference=f.order.reference,
            note="Recorded before the ledger existed"))
    for p in P.objects.all():
        rows = F.objects.filter(payout_id=p.pk)
        p.gross_sales = sum((r.subtotal for r in rows), 0)
        p.commission = sum((r.commission for r in rows), 0)
        p.processed_at = p.paid_at
        p.processed_by_id = p.recorded_by_id
        p.save(update_fields=["gross_sales", "commission", "processed_at", "processed_by"])
        E.objects.get_or_create(key=f"payout:{p.reference}", defaults=dict(
            vendor_id=p.vendor_id, kind="payout", amount=-p.amount, payout_id=p.pk, reference=p.reference,
            note="Recorded before the ledger existed"))


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_multivendor'),
        ('marketplace', '0001_initial'),
        ('orders', '0006_multivendor'),
        ('parties', '0003_alter_customer_preferred_channel'),
        ('returns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorpayout',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='auto_publish_reviews',
            field=models.BooleanField(default=True, help_text='Customer reviews go live at once (staff can still hide them); off = wait for approval'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='return_window_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Days after delivery during which customers can ask to return items', validators=[django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='vendorfulfillment',
            name='issue_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorfulfillment',
            name='issue_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorfulfillment',
            name='issue_resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorfulfillment',
            name='issue_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorfulfillment',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('cannot_fulfill', "Can't fulfil the order"), ('item_unavailable', 'Item unavailable'), ('stock_discrepancy', 'Stock count was wrong'), ('damaged_item', 'Item damaged'), ('other', 'Other fulfilment problem')], max_length=20),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='adjustments',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='destination',
            field=models.CharField(blank=True, help_text='Payout account at the time (snapshot)', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='gross_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Who recorded the outcome', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='refund_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='paid', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Who created the payout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='marketplace.payoutbatch'),
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('business_license', 'Business licence'), ('tin_certificate', 'TIN certificate'), ('registration', 'Registration certificate'), ('id', "Owner's ID"), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to=apps.marketplace.models.vendor_document_path)),
                ('content_type', models.CharField(max_length=100)),
                ('original_name', models.CharField(blank=True, help_text='Shown to staff only', max_length=150)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.vendor')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('published', 'Published'), ('pending', 'Waiting for approval'), ('flagged', 'Flagged for review'), ('hidden', 'Hidden by AGIZA')], db_index=True, default='published', max_length=10)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('vendor_reply', models.TextField(blank=True, max_length=1000)),
                ('vendor_replied_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_note', models.CharField(blank=True, max_length=255)),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='parties.customer')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(blank=True, help_text='The purchase that allows this review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
                ('vendor', models.ForeignKey(blank=True, help_text='Seller of the product when reviewed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='catalog.vendor')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product', 'status'], name='marketplace_product_5f9f90_idx'), models.Index(fields=['vendor', 'status'], name='marketplace_vendor__818ce2_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'customer'), name='one_review_per_customer_product'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_1_to_5')],
            },
        ),
        migrations.CreateModel(
            name='VendorLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('earning', 'Sale earnings (order delivered and paid)'), ('refund', 'Refund deducted'), ('adjustment', 'Adjustment'), ('payout', 'Payout'), ('payout_reversal', 'Payout failed / reversed')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('reference', models.CharField(blank=True, help_text='Order, return or payout reference', max_length=80)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fulfillment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='marketplace.vendorfulfillment')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='marketplace.vendorpayout')),
                ('return_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='returns.returnrequest')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='catalog.vendor')),
            ],
            options={
                'verbose_name_plural': 'vendor ledger entries',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['vendor', 'kind'], name='marketplace_vendor__7aaf14_idx')],
            },
        ),
        migrations.RunPython(backfill_ledger, migrations.RunPython.noop),
    ]
