# Generated by Django 5.2.17 on 2026-09-25 19:23

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_reference_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('specialized', 'Specialized'), ('restricted', 'Restricted'), ('oversized', 'Oversized'), ('manual', 'Manual')], default='standard', max_length=12)),
                ('handling', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('contains_battery', 'Contains battery'), ('fragile', 'Fragile'), ('electronics', 'Electronics'), ('hazardous', 'Hazardous material'), ('restricted', 'Restricted handling'), ('special_documentation', 'Special documentation'), ('temperature_controlled', 'Temperature controlled'), ('oversized', 'Oversized'), ('other', 'Other')], max_length=32), blank=True, default=list, size=None)),
                ('notes', models.TextField(blank=True, help_text='Restrictions / notes')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('type', models.CharField(choices=[('local', 'Local'), ('international', 'International')], default='local', max_length=14)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('type', models.CharField(choices=[('international_air', 'International Air'), ('international_sea', 'International Sea'), ('local_ground', 'Local Ground'), ('local_delivery', 'Local Delivery'), ('express_courier', 'Express Courier')], max_length=24)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('specializations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('destinations', models.ManyToManyField(blank=True, related_name='carriers_shipping_to', to='locations.country')),
                ('origins', models.ManyToManyField(blank=True, related_name='carriers_shipping_from', to='locations.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EngineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_currency', models.CharField(choices=[('TZS', 'TSh — Tanzanian Shilling'), ('USD', 'USD — US Dollar'), ('AED', 'AED — UAE Dirham'), ('CNY', 'CNY — Chinese Yuan')], default='TZS', max_length=3)),
                ('international_currency', models.CharField(choices=[('TZS', 'TSh — Tanzanian Shilling'), ('USD', 'USD — US Dollar'), ('AED', 'AED — UAE Dirham'), ('CNY', 'CNY — Chinese Yuan')], default='USD', max_length=3)),
                ('display_currency', models.CharField(choices=[('TZS', 'TSh — Tanzanian Shilling'), ('USD', 'USD — US Dollar'), ('AED', 'AED — UAE Dirham'), ('CNY', 'CNY — Chinese Yuan')], default='TZS', max_length=3)),
                ('exchange_rate_source', models.CharField(choices=[('manual', 'Manual (set rate below)'), ('auto', 'Auto (live rate API)')], default='manual', max_length=10)),
                ('default_volumetric_divisor', models.PositiveIntegerField(choices=[(5000, '5,000 (standard air)'), (6000, '6,000 (IATA standard)'), (3000, '3,000 (sea/express)'), (4000, '4,000 (custom)')], default=5000)),
                ('no_rule_fallback', models.CharField(choices=[('manual_quote', 'Return Manual Quote'), ('block', 'Block checkout'), ('error', 'Return error to API')], default='manual_quote', max_length=14)),
                ('cbm_method', models.CharField(choices=[('dimensions', 'Length × Width × Height ÷ 1,000,000'), ('manual', 'Manual input only')], default='dimensions', max_length=12)),
                ('weight_rounding', models.CharField(choices=[('half_kg', 'Round up to nearest 0.5 KG'), ('one_kg', 'Round up to nearest 1 KG'), ('exact', 'Exact weight')], default='half_kg', max_length=10)),
                ('apply_minimum_charge', models.BooleanField(default=True)),
                ('show_details_to_customers', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'engine settings',
                'verbose_name_plural': 'engine settings',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.CharField(choices=[('TZS', 'TSh — Tanzanian Shilling'), ('USD', 'USD — US Dollar'), ('AED', 'AED — UAE Dirham'), ('CNY', 'CNY — Chinese Yuan')], max_length=3)),
                ('quote_currency', models.CharField(choices=[('TZS', 'TSh — Tanzanian Shilling'), ('USD', 'USD — US Dollar'), ('AED', 'AED — UAE Dirham'), ('CNY', 'CNY — Chinese Yuan')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('effective_date', models.DateField()),
                ('source', models.CharField(choices=[('manual', 'Manual (set rate below)'), ('auto', 'Auto (live rate API)')], default='manual', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['base_currency', 'quote_currency', '-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('air', 'Air'), ('sea', 'Sea'), ('land', 'Land'), ('local', 'Local')], max_length=10)),
                ('estimated_delivery', models.CharField(blank=True, help_text='e.g. "5–10 days"', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('requires_special_handling', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('carriers', models.ManyToManyField(blank=True, related_name='methods', to='shipping_engine.carrier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('local', 'Local'), ('international', 'International')], max_length=14)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='locations.city')),
                ('destination_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='locations.country')),
                ('origin_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes_from', to='locations.city')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_from', to='locations.country')),
                ('methods', models.ManyToManyField(related_name='routes', to='shipping_engine.shippingmethod')),
                ('destination_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='shipping_engine.zone')),
            ],
            options={
                'ordering': ['type', 'origin_country__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('pricing_model', models.CharField(choices=[('per_kg', 'Per KG'), ('per_cbm', 'Per CBM'), ('per_vol_weight', 'Per Vol. Weight'), ('per_item', 'Per Item'), ('fixed', 'Fixed Shipment')], max_length=16)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(choices=[('TZS', 'TSh — Tanzanian Shilling'), ('USD', 'USD — US Dollar'), ('AED', 'AED — UAE Dirham'), ('CNY', 'CNY — Chinese Yuan')], max_length=3)),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.city')),
                ('destination_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.region')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overrides', to='shipping_engine.route')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overrides', to='shipping_engine.shippingprofile')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('applies_to', models.CharField(choices=[('product', 'Specific Product'), ('profile', 'Shipping Profile'), ('general', 'General Route')], default='general', max_length=10)),
                ('product_sku', models.CharField(blank=True, db_index=True, max_length=64)),
                ('pricing_model', models.CharField(choices=[('per_kg', 'Per KG'), ('per_cbm', 'Per CBM'), ('per_vol_weight', 'Per Vol. Weight'), ('per_item', 'Per Item'), ('fixed', 'Fixed Shipment'), ('manual', 'Manual Quote')], max_length=16)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(choices=[('TZS', 'TSh — Tanzanian Shilling'), ('USD', 'USD — US Dollar'), ('AED', 'AED — UAE Dirham'), ('CNY', 'CNY — Chinese Yuan')], max_length=3)),
                ('volumetric_divisor', models.PositiveIntegerField(blank=True, choices=[(5000, '5,000 (standard air)'), (6000, '6,000 (IATA standard)'), (3000, '3,000 (sea/express)'), (4000, '4,000 (custom)')], null=True)),
                ('min_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_cbm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_cbm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_volumetric_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_volumetric_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('minimum_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('eta_min_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('eta_max_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='shipping_engine.carrier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='shipping_engine.shippingmethod')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='shipping_engine.shippingprofile')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='shipping_engine.route')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.region')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='shipping_engine.zone')),
            ],
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['status'], name='shipping_en_status_34c62e_idx'),
        ),
        migrations.AddConstraint(
            model_name='enginesettings',
            constraint=models.CheckConstraint(condition=models.Q(('pk', 1)), name='engine_settings_singleton'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['base_currency', 'quote_currency', '-effective_date'], name='shipping_en_base_cu_18c01d_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'effective_date'), name='uniq_exchange_rate_per_day'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(condition=models.Q(('base_currency', models.F('quote_currency')), _negated=True), name='exchange_rate_distinct_currencies'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='exchange_rate_positive'),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['category', 'status'], name='shipping_en_categor_bdddae_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleoverride',
            index=models.Index(fields=['route', 'status', 'start_date', 'end_date'], name='shipping_en_route_i_8b7516_idx'),
        ),
        migrations.AddConstraint(
            model_name='ruleoverride',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='override_dates'),
        ),
        migrations.AddConstraint(
            model_name='ruleoverride',
            constraint=models.CheckConstraint(condition=models.Q(('destination_city__isnull', True), ('destination_region__isnull', True), _connector='OR'), name='override_single_destination'),
        ),
        migrations.AddIndex(
            model_name='shippingrule',
            index=models.Index(fields=['route', 'method', 'status'], name='shipping_en_route_i_92819a_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingrule',
            index=models.Index(fields=['applies_to'], name='shipping_en_applies_39f45b_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingrule',
            constraint=models.CheckConstraint(condition=models.Q(('pricing_model', 'manual'), ('rate__isnull', False), _connector='OR'), name='rule_rate_required_unless_manual'),
        ),
        migrations.AddConstraint(
            model_name='shippingrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applies_to', 'general'), ('product_sku', ''), ('profile__isnull', True)), models.Q(('applies_to', 'profile'), ('product_sku', ''), ('profile__isnull', False)), models.Q(('applies_to', 'product'), ('profile__isnull', True), models.Q(('product_sku', ''), _negated=True)), _connector='OR'), name='rule_applies_to_target'),
        ),
        migrations.AddConstraint(
            model_name='shippingrule',
            constraint=models.CheckConstraint(condition=models.Q(('volumetric_divisor__isnull', True), ('pricing_model', 'per_vol_weight'), _connector='OR'), name='rule_divisor_only_for_vol_weight'),
        ),
        migrations.AddConstraint(
            model_name='shippingrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_weight_kg__isnull', True), ('max_weight_kg__isnull', True), ('min_weight_kg__lte', models.F('max_weight_kg')), _connector='OR'), name='rule_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='shippingrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_cbm__isnull', True), ('max_cbm__isnull', True), ('min_cbm__lte', models.F('max_cbm')), _connector='OR'), name='rule_cbm_range'),
        ),
        migrations.AddConstraint(
            model_name='shippingrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_volumetric_kg__isnull', True), ('max_volumetric_kg__isnull', True), ('min_volumetric_kg__lte', models.F('max_volumetric_kg')), _connector='OR'), name='rule_vol_range'),
        ),
        migrations.AddConstraint(
            model_name='shippingrule',
            constraint=models.CheckConstraint(condition=models.Q(('eta_min_days__isnull', True), ('eta_max_days__isnull', True), ('eta_min_days__lte', models.F('eta_max_days')), _connector='OR'), name='rule_eta_range'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['type', 'status'], name='shipping_en_type_810752_idx'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('destination_city__isnull', True), ('destination_country__isnull', True), ('destination_zone__isnull', False)), models.Q(('destination_country__isnull', False), ('destination_zone__isnull', True)), _connector='OR'), name='route_destination_zone_xor_country'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('origin_country', 'origin_city', 'destination_country', 'destination_city', 'destination_zone'), name='uniq_route', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='zonedestination',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('city__isnull', False), ('country__isnull', True), ('region__isnull', True)), models.Q(('city__isnull', True), ('country__isnull', True), ('region__isnull', False)), models.Q(('city__isnull', True), ('country__isnull', False), ('region__isnull', True)), _connector='OR'), name='zone_destination_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='zonedestination',
            constraint=models.UniqueConstraint(condition=models.Q(('city__isnull', False)), fields=('city',), name='uniq_zone_city'),
        ),
        migrations.AddConstraint(
            model_name='zonedestination',
            constraint=models.UniqueConstraint(condition=models.Q(('region__isnull', False)), fields=('region',), name='uniq_zone_region'),
        ),
        migrations.AddConstraint(
            model_name='zonedestination',
            constraint=models.UniqueConstraint(condition=models.Q(('country__isnull', False)), fields=('country',), name='uniq_zone_country'),
        ),
    ]
