# Generated by Django 5.2.17 on 2026-09-26 00:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_reference_data'),
        ('shipping_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('air_cargo', 'Air cargo'), ('sea_cargo', 'Sea cargo'), ('local_land_cargo', 'Local land cargo')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='carrier',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='shippers', to='locations.warehouse'),
        ),
    ]
