# Generated by Django 5.2.17 on 2026-09-26 12:06

"""
EngineSettings gets a plain (not auto-increment) primary key so its singleton
CHECK (id = 1) is accepted by MySQL.

Databases built from the squashed 0001 already have it. Databases built from
the original 0001/0002 had an identity column; Django describes them through
the squashed migration too, so the AlterField below can be a no-op for them and
the RunPython drops the leftover identity (PostgreSQL only, idempotent).
"""
from django.db import migrations, models


def drop_leftover_identity(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    qn = schema_editor.quote_name
    schema_editor.execute(f"ALTER TABLE {qn('shipping_engine_enginesettings')} ALTER COLUMN {qn('id')} DROP IDENTITY IF EXISTS")


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_engine', '0003_portable_list_fields_and_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginesettings',
            name='id',
            field=models.BigIntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RunPython(drop_leftover_identity, migrations.RunPython.noop, elidable=True),
    ]
