# Generated by Django 5.2.17 on 2026-10-01 08:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_multivendor'),
        ('locations', '0003_multivendor'),
        ('shipping_engine', '0004_engine_settings_plain_pk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enginesettings',
            name='import_payment_window_hours',
            field=models.PositiveIntegerField(default=48, help_text='Orders with imported items are cancelled if not fully paid within this many hours of ordering', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='ImportCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(help_text='Shown to customers, e.g. "Import duty"', max_length=120)),
                ('kind', models.CharField(choices=[('customs_duty', 'Customs / import duty'), ('import_vat', 'Import VAT'), ('excise', 'Excise duty'), ('clearance', 'Clearance / handling fee'), ('other', 'Other import charge')], default='customs_duty', max_length=14)),
                ('product_sku', models.CharField(blank=True, help_text='Empty: any product', max_length=64)),
                ('basis', models.CharField(choices=[('percent', 'Percentage of value'), ('fixed_item', 'Fixed amount per item'), ('fixed_shipment', 'Fixed amount per order')], default='percent', max_length=14)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Percent (e.g. 25 for 25%) or a fixed amount in `currency`', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(blank=True, choices=[('TZS', 'TSh — Tanzanian Shilling'), ('USD', 'USD — US Dollar'), ('AED', 'AED — UAE Dirham'), ('CNY', 'CNY — Chinese Yuan')], help_text='For fixed amounts (converted with the exchange rates)', max_length=3)),
                ('percent_base', models.CharField(choices=[('goods', 'Goods value'), ('goods_shipping', 'Goods + international shipping')], default='goods', max_length=14)),
                ('treatment', models.CharField(choices=[('included', 'Charged at checkout'), ('estimate', 'Estimate only (paid separately)')], default='estimate', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Internal: legal basis, source of the rate')),
                ('category', models.ForeignKey(blank=True, help_text='Empty: any category', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('origin_country', models.ForeignKey(blank=True, help_text='Empty: imports from any country', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.country')),
                ('profile', models.ForeignKey(blank=True, help_text='Empty: any shipping profile', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shipping_engine.shippingprofile')),
            ],
            options={
                'ordering': ['kind', 'name', 'id'],
                'indexes': [models.Index(fields=['status', 'kind'], name='shipping_en_status_e83be4_idx')],
            },
        ),
    ]
