# Generated by Django 5.2.17 on 2026-09-26 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('assignment', 'Assignment'), ('escalation', 'Escalation'), ('follow_up', 'Follow-up due'), ('approval', 'Approval needed'), ('message', 'New message'), ('system', 'System')], max_length=12)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('link', models.CharField(blank=True, help_text='App path, e.g. /chat?open=12', max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx')],
            },
        ),
    ]
