# Generated by Django 5.2.17 on 2026-09-30 08:58

from django.db import migrations, models


def seller_notifications_to_seller_app(apps, schema_editor):
    """Store owners' notifications (data.type == "seller") now live in the seller app's inbox."""
    CustomerNotification = apps.get_model("storefront", "CustomerNotification")
    CustomerNotification.objects.filter(data__type="seller").update(audience="seller")


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_alter_customer_preferred_channel'),
        ('storefront', '0002_production_readiness'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customernotification',
            name='storefront__custome_1b154d_idx',
        ),
        migrations.AddField(
            model_name='customernotification',
            name='audience',
            field=models.CharField(choices=[('customer', 'Customer app'), ('seller', 'Seller app')], default='customer', max_length=10),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='app',
            field=models.CharField(choices=[('customer', 'Customer app'), ('seller', 'Seller app')], default='customer', max_length=10),
        ),
        migrations.AddIndex(
            model_name='customernotification',
            index=models.Index(fields=['customer', 'audience', 'read_at'], name='storefront__custome_bf6e82_idx'),
        ),
        migrations.RunPython(seller_notifications_to_seller_app, migrations.RunPython.noop),
    ]
