# Generated by Django 5.2.17 on 2026-09-25 23:43

import apps.deliveries.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_reference_data'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('delivery_type', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('same_day', 'Same Day'), ('inter_city', 'Inter-City')], default='standard', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned_driver', 'Assigned Driver'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('rescheduled', 'Rescheduled'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_point', models.CharField(blank=True, max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('destination_area', models.CharField(blank=True, max_length=120)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('recipient_phone', models.CharField(blank=True, max_length=32)),
                ('exception_flag', models.CharField(blank=True, choices=[('customer_unavailable', 'Customer Unavailable'), ('payment_issue', 'Payment Issue'), ('address_unclear', 'Address Unclear')], max_length=24)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.city')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='orders.order')),
                ('pickup_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.warehouse')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='deliveries.delivery')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.deliveries.models.proof_path)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='deliveries.delivery')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='proof', serialize=False, to='deliveries.delivery')),
                ('signature_name', models.CharField(max_length=150)),
                ('signature_image', models.FileField(blank=True, upload_to=apps.deliveries.models.proof_path)),
                ('signature_content_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField()),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['driver', 'status'], name='deliveries__driver__3b562f_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['scheduled_at'], name='deliveries__schedul_b5bb8f_idx'),
        ),
    ]
