# Generated by Django 5.2.17 on 2026-09-29 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_multivendor'),
        ('deliveries', '0001_initial'),
        ('locations', '0003_multivendor'),
        ('marketplace', '0001_initial'),
        ('orders', '0006_multivendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for the seller'), ('ready', 'Ready to collect'), ('assigned', 'Rider assigned'), ('collected', 'Collected'), ('at_hub', 'At AGIZA hub'), ('cancelled', 'Cancelled'), ('failed', 'Collection failed')], db_index=True, default='pending', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('handed_over_by', models.CharField(blank=True, help_text='Who handed the items over at the seller', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('destination', models.ForeignKey(help_text='The AGIZA hub the items are brought to', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.warehouse')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_tasks', to=settings.AUTH_USER_MODEL)),
                ('fulfillment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_task', to='marketplace.vendorfulfillment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_tasks', to='orders.order')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.warehouse')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.vendor')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PickupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=10)),
                ('to_status', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='deliveries.pickuptask')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='pickuptask',
            index=models.Index(fields=['driver', 'status'], name='deliveries__driver__e819b2_idx'),
        ),
    ]
