# Generated by Django 5.2.17 on 2026-10-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_production_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='item_labels',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
