# Generated by Django 5.2.17 on 2026-09-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=32, unique=True)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'reference sequence',
            },
        ),
    ]
