# Generated by Django 5.2.17 on 2026-09-25 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('seed', models.CharField(help_text="Seed set that created the row, e.g. 'shipping'", max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['seed'], name='core_seedre_seed_f94a31_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='uniq_seed_record')],
            },
        ),
    ]
