# Generated by Django 5.2.17 on 2026-09-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_serviceprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='preferred_channel',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('web', 'Web'), ('phone', 'Phone'), ('walk_in', 'Walk-in'), ('app', 'Mobile app')], max_length=10),
        ),
    ]
