# Generated by Django 5.2.17 on 2026-09-25 22:28

import apps.orders.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('order_type', models.CharField(choices=[('express', 'Express Delivery'), ('international', 'International'), ('equipment', 'Equipment Support')], max_length=16)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('item_details', models.CharField(help_text='e.g. "2x Electronics Package (5kg)"', max_length=255)),
                ('department', models.CharField(choices=[('unassigned', 'Unassigned'), ('procurement', 'Procurement'), ('shipping', 'Shipping'), ('delivery', 'Delivery'), ('support', 'Support')], default='unassigned', max_length=16)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('installment_plan', models.BooleanField(default=False, help_text='Customer pays in installments')),
                ('installment_allowed', models.BooleanField(default=False, help_text='Admin approved proceeding on installments')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='parties.customer')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.orders.models.attachment_path)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('caption', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'order status history',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('other', 'Other')], max_length=16)),
                ('kind', models.CharField(choices=[('advance', 'Advance'), ('installment', 'Installment'), ('balance', 'Balance / Full'), ('refund', 'Refund')], default='balance', max_length=12)),
                ('reference', models.CharField(blank=True, help_text='Receipt / transaction number', max_length=80)),
                ('paid_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentDetails',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='equipment', serialize=False, to='orders.order')),
                ('service_type', models.CharField(choices=[('installation', 'Installation'), ('product_setup', 'Product Setup'), ('maintenance', 'Maintenance'), ('electronic_repair', 'Electronic Repair')], max_length=20)),
                ('equipment', models.CharField(max_length=160)),
                ('classification', models.CharField(choices=[('simple', 'Simple'), ('bulk', 'Bulk'), ('machinery', 'Machinery'), ('fragile', 'Fragile')], default='simple', max_length=12)),
                ('site_address', models.CharField(blank=True, max_length=255)),
                ('technician_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('expected_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('needs_attention', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExpressDetails',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='express', serialize=False, to='orders.order')),
                ('pickup_address', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('urgent', 'Urgent')], default='standard', max_length=10)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('package_size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=8)),
                ('customer_package_size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text='Size the customer selected', max_length=8)),
                ('estimated_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('advance_required', models.BooleanField(default=False)),
                ('advance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalDetails',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='international', serialize=False, to='orders.order')),
                ('order_class', models.CharField(choices=[('simple', 'Simple'), ('bulk', 'Bulk'), ('machinery', 'Machinery'), ('fragile', 'Fragile')], default='simple', max_length=12)),
                ('service_type', models.CharField(choices=[('full_service', 'Full Service (Agiza sourcing)'), ('deliver_for_me', 'Deliver for Me'), ('local_purchase', 'Local Purchase'), ('marketplace', 'Marketplace')], default='full_service', max_length=16)),
                ('supplier_name', models.CharField(blank=True, max_length=150)),
                ('tracking_number', models.CharField(blank=True, max_length=80)),
                ('item_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
