# Generated by Django 5.2.17 on 2026-09-26 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_purchase_cost_order_shipping_cost_and_more'),
        ('parties', '0002_serviceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdetails',
            name='service_provider',
            field=models.ForeignKey(blank=True, help_text='External provider doing the work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='parties.serviceprovider'),
        ),
    ]
