# Generated by Django 5.2.17 on 2026-09-29 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_equipmentdetails_service_provider'),
        ('parties', '0003_alter_customer_preferred_channel'),
        ('shipping_engine', '0004_engine_settings_plain_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='delivery_address',
            field=models.ForeignKey(blank=True, help_text='Saved address the customer chose', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='parties.address'),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='estimated_delivery',
            field=models.CharField(blank=True, help_text='Quoted at checkout, e.g. "1–2 days"', max_length=60),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='payment_preference',
            field=models.CharField(blank=True, choices=[('pay_later', 'Pay later (cash, bank or mobile money to AGIZA)'), ('mobile_money', 'Mobile money (Selcom checkout)')], max_length=16),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shipping_engine.shippingmethod'),
        ),
    ]
