# Generated by Django 5.2.17 on 2026-09-29 17:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_vendor(apps, schema_editor):
    """Existing order lines: record who sold them. Commission stays empty (orders placed before the marketplace)."""
    OrderItem = apps.get_model("orders", "OrderItem")
    for item in OrderItem.objects.select_related("variant__product").filter(vendor__isnull=True):
        if item.variant.product.vendor_id:
            OrderItem.objects.filter(pk=item.pk).update(vendor_id=item.variant.product.vendor_id)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_multivendor'),
        ('marketplace', '0001_initial'),
        ('orders', '0005_shopdetails_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='marketplace.vendorfulfillment'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Empty = sold by AGIZA', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.vendor'),
        ),
        migrations.RunPython(backfill_vendor, migrations.RunPython.noop),
    ]
