# Generated by Django 5.2.17 on 2026-09-29 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_production_readiness'),
        ('orders', '0006_multivendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Change to the total (negative = lower)', max_digits=14)),
                ('total_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fulfillment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_adjustments', to='marketplace.vendorfulfillment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='orders.order')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
