# Generated by Django 5.2.17 on 2026-09-30 00:28

import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Refunds recorded before this change left the order total as it was, so the refund showed up as
    a balance due. Lower each such order's total with an explicit adjustment (once per return)."""
    ReturnRequest = apps.get_model("returns", "ReturnRequest")
    OrderAdjustment = apps.get_model("orders", "OrderAdjustment")
    Order = apps.get_model("orders", "Order")
    refunded = (ReturnRequest.objects.filter(refund_payment__isnull=False)
                .exclude(return_type="seller_cannot_fulfill").order_by("closed_at", "id"))
    for ret in refunded:
        if OrderAdjustment.objects.filter(return_request=ret).exists() or not ret.refund_amount:
            continue
        order = Order.objects.select_for_update().get(pk=ret.order_id)
        if order.total_amount is None:
            continue
        before = order.total_amount
        after = max(before - ret.refund_amount, Decimal("0"))
        OrderAdjustment.objects.create(order=order, amount=after - before, total_before=before, total_after=after,
                                       return_request=ret, reason=f"Return {ret.reference} refunded"[:255])
        Order.objects.filter(pk=order.pk).update(total_amount=after)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_production_readiness'),
        ('returns', '0002_production_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderadjustment',
            name='return_request',
            field=models.ForeignKey(blank=True, help_text='The refunded return, if any', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_adjustments', to='returns.returnrequest'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
