# Generated by Django 5.2.17 on 2026-10-01 08:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_refund_adjustments'),
        ('shipping_engine', '0005_import_charges_and_payment_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sourced_abroad',
            field=models.BooleanField(default=False, help_text='Imported item bought for this order (no stock was reserved)'),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='customs_charges',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown quoted at checkout'),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='customs_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='customs_status',
            field=models.CharField(blank=True, help_text='included / estimated / not_included (empty: nothing imported)', max_length=14),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='import_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Part of delivery_fee for shipping imported items to Tanzania', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='import_shipping_method',
            field=models.ForeignKey(blank=True, help_text='How the imported items travel to Tanzania', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shipping_engine.shippingmethod'),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='payment_due_at',
            field=models.DateTimeField(blank=True, help_text='Prepaid orders are cancelled if not fully paid by then', null=True),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='prepayment_required',
            field=models.BooleanField(default=False, help_text='Imported items: AGIZA buys them only once the order is fully paid'),
        ),
    ]
