# Generated by Django 5.2.17 on 2026-10-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_imported_items_customs_and_payment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='delivery_fee_pending',
            field=models.BooleanField(default=False, help_text="Waiting for staff to set the delivery cost; the order can't be paid until then"),
        ),
    ]
