# Generated by Django 5.2.17 on 2026-10-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_shopdetails_delivery_fee_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='delivery_issue',
            field=models.TextField(blank=True),
        ),
    ]
