# Generated by Django 5.2.17 on 2026-09-26 00:11

import apps.catalog.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_reference_data'),
        ('shipping_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('country', models.CharField(blank=True, help_text='Country of origin', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('logo', models.FileField(blank=True, upload_to=apps.catalog.models.brand_logo_path)),
                ('logo_content_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('orange', 'Orange'), ('green', 'Green'), ('gray', 'Gray')], default='blue', max_length=10)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('type', models.CharField(choices=[('size', 'Size'), ('color', 'Color'), ('bundle', 'Bundle'), ('storage', 'Storage'), ('text', 'Text / Other')], default='text', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Set for a subcategory', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEstimateRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_days', models.PositiveSmallIntegerField()),
                ('max_days', models.PositiveSmallIntegerField()),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.city')),
            ],
            options={
                'ordering': ['from_city__name', 'to_city__name'],
            },
        ),
        migrations.CreateModel(
            name='OriginEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('air', 'Air'), ('sea', 'Sea')], max_length=3)),
                ('min_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(365)])),
                ('max_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(365)])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.country')),
            ],
            options={
                'ordering': ['country__name', 'method'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('hidden', 'Hidden'), ('out_of_stock', 'Out of Stock'), ('inactive', 'Inactive')], db_index=True, default='draft', max_length=14)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('open_box', 'Open Box')], default='new', max_length=12)),
                ('condition_description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, help_text='What Agiza pays per unit', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('low_stock_threshold', models.PositiveIntegerField(default=3)),
                ('pata_bei', models.BooleanField(default=False, help_text='Keep visible for "Pata Bei" quotations when out of stock')),
                ('location_kind', models.CharField(choices=[('warehouse', 'Agiza warehouse / shop'), ('vendor', 'Vendor Location (not Agiza warehouse)'), ('transit', 'In Transit')], default='warehouse', max_length=10)),
                ('bin_code', models.CharField(blank=True, max_length=40)),
                ('stock_override', models.CharField(blank=True, choices=[('', 'Auto (from stock qty)'), ('in_stock', 'In Stock'), ('reserved', 'Reserved'), ('in_transit', 'In Transit')], default='', max_length=12)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('packages', models.PositiveSmallIntegerField(default=1)),
                ('ready_to_ship_days', models.PositiveSmallIntegerField(default=1)),
                ('shipping_notes', models.TextField(blank=True)),
                ('has_variations', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('vendor_sku', models.CharField(blank=True, max_length=64)),
                ('vendor_location', models.CharField(blank=True, max_length=120)),
                ('vendor_profit_type', models.CharField(blank=True, choices=[('fixed', 'Fixed Amount (TSh)'), ('percent', 'Percentage (%)')], max_length=10)),
                ('vendor_profit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('featured', models.BooleanField(default=False)),
                ('ofa_kali', models.BooleanField(default=False)),
                ('allow_save', models.BooleanField(default=True)),
                ('allow_chat', models.BooleanField(default=True)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('gift_eligible', models.BooleanField(default=False)),
                ('tax_category', models.CharField(choices=[('standard', 'Standard Rate (VAT 18%)'), ('zero', 'Zero Rated'), ('exempt', 'Exempt'), ('special', 'Special Goods')], default='standard', max_length=10)),
                ('vat_applicable', models.BooleanField(default=True)),
                ('bought_together', models.ManyToManyField(blank=True, related_name='bought_with', to='catalog.product')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gifts', models.ManyToManyField(blank=True, related_name='gift_for', to='catalog.product')),
                ('labels', models.ManyToManyField(blank=True, related_name='products', to='catalog.label')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='located_products', to='locations.warehouse')),
                ('origin_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.country')),
                ('related_products', models.ManyToManyField(blank=True, related_name='related_to', to='catalog.product')),
                ('shipping_methods', models.ManyToManyField(blank=True, related_name='products', to='shipping_engine.shippingmethod')),
                ('shipping_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shipping_engine.shippingprofile')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategory_products', to='catalog.category')),
                ('variation_options', models.ManyToManyField(blank=True, related_name='products', to='catalog.productoption')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.productoption')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "128GB / Midnight Black"; "Default" for single products', max_length=120)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Empty = product price', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('out_of_stock', 'Out of Stock')], default='active', max_length=14)),
                ('notes', models.TextField(blank=True)),
                ('option_values', models.ManyToManyField(blank=True, related_name='variants', to='catalog.productoptionvalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['-is_default', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.catalog.models.product_image_path)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-is_primary', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(default='Agiza E-commerce Store', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('same_city_min_days', models.PositiveSmallIntegerField(default=1)),
                ('same_city_max_days', models.PositiveSmallIntegerField(default=2)),
                ('regional_min_days', models.PositiveSmallIntegerField(default=3)),
                ('regional_max_days', models.PositiveSmallIntegerField(default=5)),
                ('guest_checkout', models.BooleanField(default=True)),
                ('product_reviews', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.city')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'store settings',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('profit_type', models.CharField(choices=[('fixed', 'Fixed Amount (TSh)'), ('percent', 'Percentage (%)')], default='percent', max_length=10)),
                ('profit_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('profit_scope', models.CharField(choices=[('all', 'Apply to All Products'), ('per_product', 'Configure Per Product')], default='all', max_length=12)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('profit_type', 'percent'), _negated=True), ('profit_value__lte', 100), _connector='OR'), name='vendor_percent_at_most_100')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.vendor'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_category_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='uniq_top_category_name'),
        ),
        migrations.AddConstraint(
            model_name='deliveryestimateroute',
            constraint=models.UniqueConstraint(fields=('from_city', 'to_city'), name='uniq_estimate_route'),
        ),
        migrations.AddConstraint(
            model_name='deliveryestimateroute',
            constraint=models.CheckConstraint(condition=models.Q(('min_days__lte', models.F('max_days'))), name='estimate_route_range'),
        ),
        migrations.AddConstraint(
            model_name='originestimate',
            constraint=models.UniqueConstraint(fields=('country', 'method'), name='uniq_origin_estimate'),
        ),
        migrations.AddConstraint(
            model_name='originestimate',
            constraint=models.CheckConstraint(condition=models.Q(('min_days__lte', models.F('max_days'))), name='origin_estimate_range'),
        ),
        migrations.AddConstraint(
            model_name='productoptionvalue',
            constraint=models.UniqueConstraint(fields=('option', 'value'), name='uniq_option_value'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='one_default_variant'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('variant__isnull', True)), fields=('product',), name='one_primary_product_image'),
        ),
        migrations.AddConstraint(
            model_name='storesettings',
            constraint=models.CheckConstraint(condition=models.Q(('same_city_min_days__lte', models.F('same_city_max_days'))), name='store_same_city_range'),
        ),
        migrations.AddConstraint(
            model_name='storesettings',
            constraint=models.CheckConstraint(condition=models.Q(('regional_min_days__lte', models.F('regional_max_days'))), name='store_regional_range'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='catalog_pro_categor_da0f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor'], name='catalog_pro_vendor__6d8917_idx'),
        ),
    ]
