# Generated by Django 5.2.17 on 2026-09-26 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_vendor_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='uniq_top_category_name',
        ),
        migrations.RemoveConstraint(
            model_name='productimage',
            name='one_primary_product_image',
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='one_default_variant',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(models.Case(models.When(parent__isnull=True, then='name')), name='uniq_top_category_name'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(models.Case(models.When(is_primary=True, then='product', variant__isnull=True)), name='one_primary_product_image'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(models.Case(models.When(is_default=True, then='product')), name='one_default_variant'),
        ),
    ]
