# Generated by Django 5.2.17 on 2026-09-29 17:09

import apps.catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify

RESERVED = {"agiza", "admin", "api", "new", "apply", "seller", "sell", "stores", "store"}


def backfill(apps, schema_editor):
    """Give existing vendors a store slug and index existing products for search (no other data changes)."""
    from apps.catalog.search import product_search_text

    Vendor = apps.get_model("catalog", "Vendor")
    Product = apps.get_model("catalog", "Product")
    used = set()
    for vendor in Vendor.objects.order_by("pk"):
        base = (slugify(vendor.name) or "store")[:150]
        slug, n = base, 1
        while slug in used or slug in RESERVED:
            n += 1
            slug = f"{base}-{n}"
        used.add(slug)
        Vendor.objects.filter(pk=vendor.pk).update(slug=slug)
    for product in Product.objects.select_related("brand", "category", "subcategory", "vendor"):
        Product.objects.filter(pk=product.pk).update(search_text=product_search_text(product))


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_category_uniq_top_category_name_and_more'),
        ('locations', '0003_multivendor'),
        ('storefront', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='review_status',
            field=models.CharField(choices=[('not_required', 'No review needed'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disabled', 'Disabled by AGIZA')], db_index=True, default='not_required', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='search_text',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='vendor',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Application received'), ('under_review', 'Under review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='banner',
            field=models.FileField(blank=True, upload_to=apps.catalog.models.vendor_media_path),
        ),
        migrations.AddField(
            model_name='vendor',
            name='banner_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual / sole trader'), ('company', 'Registered company')], max_length=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.city'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='commission_mode',
            field=models.CharField(choices=[('default', 'Marketplace rates (category / default commission)'), ('custom', "This vendor's own agreement")], default='custom', max_length=8),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.FileField(blank=True, upload_to=apps.catalog.models.vendor_media_path),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner',
            field=models.OneToOneField(blank=True, help_text='AGIZA account that runs this store', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor', to='storefront.customeraccount'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payout_account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payout_account_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('mobile_money', 'Mobile money'), ('bank', 'Bank transfer')], max_length=14),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payout_provider',
            field=models.CharField(blank=True, help_text='e.g. M-Pesa, CRDB Bank', max_length=80),
        ),
        migrations.AddField(
            model_name='vendor',
            name='registration_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='vendor',
            name='review_note',
            field=models.TextField(blank=True, help_text='Last reason given to the vendor'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tin',
            field=models.CharField(blank=True, help_text='Tax identification number', max_length=30),
        ),
        migrations.AddField(
            model_name='vendor',
            name='warehouse',
            field=models.OneToOneField(blank=True, help_text='Where the vendor keeps the stock it sells', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor', to='locations.warehouse'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(max_length=160, unique=True),
        ),
    ]
