# Generated by Django 5.2.17 on 2026-10-04 09:51

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_multivendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('image', models.FileField(blank=True, upload_to=apps.catalog.models.slider_image_path)),
                ('image_content_type', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(blank=True, help_text='Opened when the banner is tapped (optional)')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
