# Generated by Django 5.2.17 on 2026-10-08 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_mobile_sliders'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileslider',
            name='placement',
            field=models.CharField(choices=[('app', 'App'), ('website', 'Website'), ('both', 'App and website')], default='app', max_length=10),
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('banners', 'Banners'), ('products', 'Product row'), ('categories', 'Top categories'), ('category_rows', 'A row per category'), ('services', 'AGIZA services (Buy for me, Deliver for me, Stores)'), ('stores', 'Stores')], max_length=16)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(blank=True, choices=[('manual', 'Hand-picked products'), ('featured', 'Featured products'), ('deals', 'Ofa kali deals'), ('popular', 'Popular'), ('newest', 'Newest'), ('category', 'A category')], help_text='Product rows: where the products come from', max_length=10)),
                ('fill_with_newest', models.BooleanField(default=False, help_text='Top the row up with the newest products when it has too few')),
                ('limit', models.PositiveSmallIntegerField(default=12, help_text='Products (or categories / rows) to show')),
                ('categories', models.ManyToManyField(blank=True, help_text='Top categories: the ones to show (empty = the main categories)', related_name='+', to='catalog.category')),
                ('category', models.ForeignKey(blank=True, help_text="Product rows with source 'category'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeSectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='catalog.homesection')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='homesection',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='+', through='catalog.HomeSectionProduct', to='catalog.product'),
        ),
        migrations.AddConstraint(
            model_name='homesectionproduct',
            constraint=models.UniqueConstraint(fields=('section', 'product'), name='uniq_home_section_product'),
        ),
    ]
