# Generated by Django 5.2.17 on 2026-10-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_seed_website_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
