# Generated by Django 5.2.17 on 2026-09-25 18:53

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('employee_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('staff_level', models.CharField(choices=[('top_admin', 'Top Admin'), ('admin_l2', 'Admin Level 2'), ('admin_l1', 'Admin Level 1'), ('sales', 'Sales'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('data_entry', 'Data Entry'), ('driver', 'Driver')], default='data_entry', max_length=20)),
                ('department', models.CharField(choices=[('management', 'Management'), ('sales', 'Sales'), ('procurement', 'Procurement'), ('shipping', 'Shipping'), ('delivery', 'Delivery'), ('finance', 'Finance'), ('support', 'Support'), ('warehouse', 'Warehouse')], default='support', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Can log into the Django admin site.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('status_change', 'Status changed'), ('login', 'Logged in'), ('logout', 'Logged out'), ('login_failed', 'Failed login'), ('password_change', 'Password changed'), ('permission_change', 'Permission changed')], max_length=32)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_level', models.CharField(choices=[('top_admin', 'Top Admin'), ('admin_l2', 'Admin Level 2'), ('admin_l1', 'Admin Level 1'), ('sales', 'Sales'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('data_entry', 'Data Entry'), ('driver', 'Driver')], max_length=20)),
                ('module', models.CharField(choices=[('intake_quotes', 'Intake & Quotes'), ('orders', 'Orders'), ('deliveries', 'Deliveries'), ('returns', 'Returns'), ('tasks', 'Tasks'), ('procurement', 'Procurement'), ('shipping', 'Shipping & Tracking'), ('chat', 'Chat & Customer Support'), ('ecommerce', 'E-commerce Platform'), ('warehouse', 'Warehouse & Pick Up Points'), ('finance', 'Finance'), ('shipping_engine', 'Shipping Engine'), ('people', 'People'), ('audit_logs', 'Reporting & Audit Logs'), ('settings', 'Settings')], max_length=32)),
                ('access', models.CharField(choices=[('none', 'No access'), ('view', 'View'), ('edit', 'Edit'), ('manage', 'Manage')], default='none', max_length=10)),
            ],
            options={
                'ordering': ['staff_level', 'module'],
                'constraints': [models.UniqueConstraint(fields=('staff_level', 'module'), name='uniq_role_permission')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['staff_level'], name='accounts_us_staff_l_bcba6e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department'], name='accounts_us_departm_4298b0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='accounts_au_content_659137_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='accounts_au_action_5ca9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='accounts_au_created_721afe_idx'),
        ),
    ]
