from django.db import migrations

# Default access matrix approved in the Phase 1 plan. Frozen here so the
# migration stays reproducible even if constants change later.
DEFAULT_PERMISSIONS = {'admin_l2': {'intake_quotes': 'manage',
              'orders': 'manage',
              'deliveries': 'manage',
              'returns': 'manage',
              'tasks': 'manage',
              'procurement': 'manage',
              'shipping': 'manage',
              'chat': 'manage',
              'ecommerce': 'manage',
              'warehouse': 'manage',
              'finance': 'manage',
              'shipping_engine': 'manage',
              'people': 'manage',
              'audit_logs': 'manage',
              'settings': 'manage'},
 'admin_l1': {'intake_quotes': 'edit',
              'orders': 'edit',
              'deliveries': 'edit',
              'returns': 'edit',
              'tasks': 'edit',
              'procurement': 'edit',
              'shipping': 'edit',
              'chat': 'edit',
              'ecommerce': 'edit',
              'warehouse': 'edit',
              'finance': 'view',
              'shipping_engine': 'view',
              'people': 'view',
              'audit_logs': 'view',
              'settings': 'view'},
 'sales': {'intake_quotes': 'edit',
           'orders': 'edit',
           'deliveries': 'view',
           'returns': 'edit',
           'tasks': 'edit',
           'procurement': 'view',
           'shipping': 'view',
           'chat': 'edit',
           'ecommerce': 'view',
           'warehouse': 'view',
           'finance': 'view',
           'shipping_engine': 'view',
           'people': 'view',
           'audit_logs': 'none',
           'settings': 'none'},
 'finance': {'intake_quotes': 'view',
             'orders': 'view',
             'deliveries': 'view',
             'returns': 'edit',
             'tasks': 'edit',
             'procurement': 'view',
             'shipping': 'view',
             'chat': 'view',
             'ecommerce': 'view',
             'warehouse': 'view',
             'finance': 'manage',
             'shipping_engine': 'view',
             'people': 'none',
             'audit_logs': 'none',
             'settings': 'none'},
 'procurement': {'intake_quotes': 'view',
                 'orders': 'edit',
                 'deliveries': 'none',
                 'returns': 'edit',
                 'tasks': 'edit',
                 'procurement': 'manage',
                 'shipping': 'edit',
                 'chat': 'view',
                 'ecommerce': 'edit',
                 'warehouse': 'edit',
                 'finance': 'view',
                 'shipping_engine': 'view',
                 'people': 'none',
                 'audit_logs': 'none',
                 'settings': 'none'},
 'data_entry': {'intake_quotes': 'edit',
                'orders': 'edit',
                'deliveries': 'view',
                'returns': 'edit',
                'tasks': 'edit',
                'procurement': 'view',
                'shipping': 'view',
                'chat': 'none',
                'ecommerce': 'edit',
                'warehouse': 'edit',
                'finance': 'none',
                'shipping_engine': 'none',
                'people': 'none',
                'audit_logs': 'none',
                'settings': 'none'},
 'driver': {'intake_quotes': 'none',
            'orders': 'none',
            'deliveries': 'edit',
            'returns': 'none',
            'tasks': 'none',
            'procurement': 'none',
            'shipping': 'none',
            'chat': 'none',
            'ecommerce': 'none',
            'warehouse': 'none',
            'finance': 'none',
            'shipping_engine': 'none',
            'people': 'none',
            'audit_logs': 'none',
            'settings': 'none'}}


def seed(apps, schema_editor):
    RolePermission = apps.get_model("accounts", "RolePermission")
    for level, modules in DEFAULT_PERMISSIONS.items():
        for module, access in modules.items():
            RolePermission.objects.get_or_create(staff_level=level, module=module, defaults={"access": access})


def unseed(apps, schema_editor):
    apps.get_model("accounts", "RolePermission").objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [("accounts", "0001_initial")]
    operations = [migrations.RunPython(seed, unseed)]
