# Generated by Django 5.2.17 on 2026-09-25 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('task_type', models.CharField(choices=[('generate_quote', 'Generate Quote'), ('verify_payment', 'Verify Payment'), ('assign_cargo', 'Assign Cargo'), ('follow_up_client', 'Follow Up Client'), ('customs_clearance', 'Customs Clearance'), ('arrange_delivery', 'Arrange Delivery'), ('quality_check', 'Quality Check'), ('pricing_approval', 'Pricing Approval'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('waiting_for_client', 'Waiting for Client'), ('waiting_for_payment', 'Waiting for Payment'), ('blocked', 'Blocked'), ('review_required', 'Review Required'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='in_progress', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('department', models.CharField(choices=[('unassigned', 'Unassigned'), ('sales', 'Sales'), ('procurement', 'Procurement'), ('shipping', 'Shipping'), ('delivery', 'Delivery'), ('finance', 'Finance'), ('support', 'Support'), ('warehouse', 'Warehouse')], default='unassigned', max_length=12)),
                ('sla_deadline', models.DateTimeField(db_index=True)),
                ('description', models.TextField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='orders.order')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='quotes.quoterequest')),
            ],
            options={
                'ordering': ['sla_deadline', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Note'), ('status', 'Status change'), ('owner', 'Owner change'), ('created', 'Created')], max_length=10)),
                ('body', models.TextField(blank=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='tasks.task')),
            ],
            options={
                'verbose_name_plural': 'task activity',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'status'], name='tasks_task_owner_i_9240ec_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['department'], name='tasks_task_departm_4ab9c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('order__isnull', True), ('quote__isnull', True), _connector='OR'), name='task_single_link'),
        ),
    ]
