# Generated by Django 5.2.17 on 2026-09-25 23:43

import apps.shipping.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_reference_data'),
        ('orders', '0002_initial'),
        ('shipping_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_id', models.CharField(editable=False, max_length=24, unique=True)),
                ('shipment_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('booked', 'Booked'), ('loaded', 'Loaded'), ('export_cleared', 'Export Cleared'), ('shipping_to_destination', 'Shipping to Destination'), ('clearance', 'Clearance'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=24)),
                ('master_tracking_number', models.CharField(blank=True, help_text='Bill of lading / air waybill', max_length=80)),
                ('eta', models.DateField(blank=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.CharField(blank=True, choices=[('', 'All Good'), ('customs_hold', 'Customs Hold'), ('document_missing', 'Document Missing'), ('carrier_delay', 'Carrier Delay')], default='', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.city')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.country')),
                ('origin_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_shipments', to='locations.warehouse')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipping_engine.carrier')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipping_engine.shippingmethod')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CargoParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('waiting', 'Waiting to Receive'), ('ready', 'Ready for Shipment'), ('in_shipment', 'In Shipment'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=12)),
                ('source', models.CharField(choices=[('agiza_procured', 'Agiza Procured'), ('client_purchased', 'Client Purchased')], max_length=20)),
                ('supplier_tracking_number', models.CharField(blank=True, max_length=80)),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('packages_quantity', models.PositiveSmallIntegerField(default=1)),
                ('estimated_arrival', models.DateField(blank=True, help_text='Expected at the consolidation warehouse', null=True)),
                ('cargo_type', models.CharField(choices=[('standard', 'Standard'), ('electronic_battery', 'Electronic w/ Battery'), ('bulk', 'Bulk'), ('machinery', 'Machinery'), ('fragile', 'Fragile')], default='standard', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cbm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('weight_type', models.CharField(choices=[('estimated', 'Estimated'), ('exact', 'Exact')], default='estimated', max_length=10)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('added_to_shipment_at', models.DateTimeField(blank=True, null=True)),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.city')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cargo', to='orders.order')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipper', models.ForeignKey(blank=True, help_text='Preferred shipper / forwarder', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='shipping_engine.carrier')),
                ('shipping_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='shipping_engine.shippingmethod')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Consolidation warehouse', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='locations.warehouse')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='shipping.shipment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.shipping.models.document_path)),
                ('name', models.CharField(max_length=160)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shipping.shipment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('status', 'Status change'), ('update', 'Tracking update'), ('parcel', 'Parcels changed'), ('alert', 'Alert')], max_length=10)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping.shipment')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['shipper'], name='shipping_sh_shipper_74f325_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['alert'], name='shipping_sh_alert_3787e4_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', 'occurred_at'], name='shipping_sh_shipmen_af7b15_idx'),
        ),
    ]
