# Generated by Django 5.2.17 on 2026-10-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoparcel',
            name='lost_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargoparcel',
            name='lost_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cargoparcel',
            name='stage',
            field=models.CharField(choices=[('waiting', 'Waiting to Receive'), ('ready', 'Ready for Shipment'), ('in_shipment', 'In Shipment'), ('arrived', 'Arrived'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=12),
        ),
    ]
