# Generated by Django 5.2.17 on 2026-10-08 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_multivendor'),
        ('shipping', '0002_parcel_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='arrival_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_shipments', to='locations.warehouse'),
        ),
    ]
