# Generated by Django 5.2.17 on 2026-09-26 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_purchase_cost_order_shipping_cost_and_more'),
        ('parties', '0001_initial'),
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'quick replies',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('web', 'Web')], max_length=10)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('web', 'Web')], max_length=10)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_handle', models.CharField(help_text='Phone number, page-scoped id or username', max_length=150)),
                ('external_thread_id', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('open', 'Open'), ('archived', 'Archived')], db_index=True, default='open', max_length=10)),
                ('response_status', models.CharField(choices=[('new', 'New'), ('waiting_team', 'Waiting for Team'), ('waiting_client', 'Waiting for Client'), ('urgent', 'Urgent')], default='new', max_length=14)),
                ('department', models.CharField(choices=[('sales', 'Sales'), ('support', 'Support'), ('delivery', 'Delivery'), ('procurement', 'Procurement'), ('finance', 'Finance'), ('management', 'Manager')], default='sales', max_length=12)),
                ('handler_since', models.DateTimeField(blank=True, null=True)),
                ('escalated_to', models.CharField(blank=True, choices=[('sales', 'Sales'), ('support', 'Support'), ('delivery', 'Delivery'), ('procurement', 'Procurement'), ('finance', 'Finance'), ('management', 'Manager')], max_length=12)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_notified', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, max_length=200)),
                ('last_customer_message_at', models.DateTimeField(blank=True, null=True)),
                ('team_read_at', models.DateTimeField(blank=True, help_text='When staff last read the conversation', null=True)),
                ('active_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_conversations', to=settings.AUTH_USER_MODEL)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='parties.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='orders.order')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='quotes.quoterequest')),
            ],
            options={
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('system', 'System'), ('internal', 'Internal note')], max_length=8)),
                ('body', models.TextField(blank=True)),
                ('delivery_status', models.CharField(blank=True, choices=[('stored', 'Saved (channel not connected)'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received')], max_length=10)),
                ('delivery_error', models.CharField(blank=True, max_length=255)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('quote', models.ForeignKey(blank=True, help_text='Quotation card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='quotes.quoterequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['channel', 'contact_handle'], name='chat_conver_channel_76bdc0_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['assigned_agent'], name='chat_conver_assigne_e5d9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
    ]
