# Generated by Django 5.2.17 on 2026-10-06 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('returns', '0002_production_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='return_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='returns.returnrequest'),
        ),
    ]
