# Generated by Django 5.2.17 on 2026-09-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_reference_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='type',
            field=models.CharField(choices=[('consolidation', 'Consolidation'), ('fulfillment', 'Fulfillment'), ('pickup_point', 'Pickup Point'), ('shop', 'Shop'), ('vendor', 'Vendor location')], max_length=20),
        ),
    ]
