# Generated by Django 5.2.17 on 2026-09-29 12:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_shopdetails_delivery_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('selcom', 'Selcom')], default='selcom', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('provider_order_id', models.CharField(help_text='Order id sent to the gateway', max_length=64, unique=True)),
                ('provider_reference', models.CharField(blank=True, help_text='Gateway transaction id', max_length=80)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('gateway_url', models.TextField(blank=True, help_text='Hosted checkout page the customer opens')),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('needs_attention', models.BooleanField(default=False, help_text='Money received but not applied (refund needed)')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('status_payload', models.JSONField(blank=True, default=dict, help_text='Last order-status answer')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gateway_payments', to='orders.order')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gateway_payment', to='orders.payment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['order', 'status'], name='payments_ga_order_i_ce53e0_idx')],
            },
        ),
    ]
